---
title: "Lab-04 Dynamic Graphics"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    css: css.css
runtime: shiny
---





```{r global, include = FALSE}

  # PROVIDED CODE

      # The following code was provided in the
      # .Rmd file used for the Lab 04 template.

      # What does it do? It "preprocesses" 
      # your data - that is, it prepares your 
      # data for the visualization and app.

      # These are also known as "variable
      # transformations", since you are trans-
      # forming existing variables to make 
      # new ones.

      # Only one additional line of code was 
      # required, which is added at the very 
      # bottom.

library(shiny)
library(tidyverse)
library(flexdashboard)
library(plotly)
library(Lahman)
library(dplyr)
data(Teams)

ave.so <- Teams$SO / Teams$G
year <- Teams$yearID

ave.so.min <- min(ave.so, na.rm = TRUE)
ave.so.max <- max(ave.so, na.rm = TRUE)

league.ave <- tapply(X = ave.so, 
                     INDEX = as.factor(year), 
                     FUN = "mean", 
                     na.rm = TRUE)

league.year <- as.numeric(names(league.ave))

  # REQUIRED ADDITIONAL CODE

      # This line takes the vector of team 
      # averages, 'ave.so', and appends it to 
      # the dataset 'Teams' as a new variable.


index <- which(Teams$yearID <= 2012 & Teams$yearID >= 1900)

teams_one<-Teams %>%
            group_by(name)%>%
            count()%>%
            arrange(desc(n)) %>%
            head(50) %>%
            pull(name)

teams_choices<-Teams[Teams$yearID >= 1970 & Teams$yearID<=2012,]
teams<-sort(unique(teams_choices$name))

 Teams<-Teams %>%
  mutate(
    league = ifelse(lgID=="NL","National",ifelse(lgID=="AL","American","NA"))
  )
 
 league<-sort(unique(Teams$league))

  # HOW IT WORKS

      # When you assign values to a non-
      # existent variable by using '$' on an 
      # existing dataset, you create a new, 
      # permanent variable in the dataset.

      # For example:
      # 'dat$new_variable <- some_vector'

      # Dataset 'dat' would now have a new 
      # variable, called 'new_variable', 
      # that contains the values of
      # vector 'some_vector'.

Teams$ave.so <- ave.so



```


<style>                     
.navbar-inverse {
    background-color: #0f618a;;
    border-color: black;
}

</style> 










Column {.sidebar}
-----------------------------------------------------------------------


Select a team to highlight on the graph.


```{r}

  # REQUIRED CODE: ADD ARGUMENT PARAMETERS

      # The following is required to set 
      # up the widgets in your app.


selectInput(
  
  
      # Specifically and respectively, it 
      # names your "reactive" object, for 
      # later use in your visualization 
      # ('inputId ='). This can be named 
      # anything that doesn't have oper-
      # ators (e.g. '$' or '>'). You just
      # have to make sure that this name 
      # is used again in 'renderPlot()'.
  
  
  inputId = "my_team",
  
  
      # It also sets up a prompt for your 
      # widget with argument 'label ='. 
      # This could be anything, but it's
      # an opportunity to guide your app
      # end users and improve their UX
      # (user experience), e.g. "Choose 
      # team." or "Pick your favorite:".
  
  
  label = "Select a team:",
  
  
      # It provides the choices available
      # for end users to select in argu-
      # ment 'choices ='. While you could
      # have used something like:
      # 'unique(Teams$name)[1:25]', you
      # may have found that many of the 
      # early-mentioned teams don't have
      # a lot 21st century data. 
      # Therefore, it's easier to name
      # teams manually within 'c()'!
  
      # Here are a few examples to get
      # you started.
  
  
  
  
  choices = teams,
  
  
      # Lastly, you can select a default 
      # value for your selected team by 
      # using argument 'selected ='. The
      # app plots this team by default.
  
  
  selected = "Boston Red Sox"
  
  )








```



<style>

.section.sidebar{
    position: fixed;
    top: 51px;
    left: 0;
    bottom: 0;
    border-right: 10px solid black;
    background-color: #0f618a;
    padding-top: 10px;
    padding-left: 10px;
    padding-right: 10px;
    visibility: hidden;
    overflow: auto;
    color: #ffffff;
}
</style>










**Author:** Rudy Meza

**Date:**  `r format(Sys.time(), '%B %d, %Y')`


Column 
-----------------------------------------------------------------------

### Strikeouts on the Rise

```{r}

renderPlot({

index <- which(Teams$yearID <= 2012 & Teams$yearID >= 1900)

Teams <- Teams[index, ]
  
index <- which(year <= 2012 & year >= 1900)

ave.so <- ave.so[index]
year <- year[index]

index <- which(league.year <= 2012 
               & league.year >= 1900)

league.ave <- league.ave[index]
league.year <- league.year[index]

team.name <- input$my_team                  # 'team.name' takes the name of selected team
                                            # Calls to 'input$' must occur in 'renderPlot({...})'

dat.one.team <- filter(Teams, 
                       name == team.name)   # Filtering to include only selected team

                                            # You now have to use 'dat.one.team' in your
                                            # visualization's code for the "highlighted"
                                            # team trend line
par(omi = c(1, 1, 0, 1)) 
par(mai = c(.5,1,.5,1))
 
plot.new()

plot.window(xlim = c(1900, 2015), 
            ylim = c(0.36, 
                     13))   # Specify dimensions

points(x = year, 
       y = ave.so,
       col = "#dddddd",              # Color
       pch = 16,                    # Shape
       cex = 0.75)                  # Size

axis(side = 1,                      # Add x-axis
     lwd = 2,                       # Line width
     hadj = -0.1,                   # Horizontal label position 
     padj = -1,                     # Vertical label position
     at = seq(from = 1900, 
              to = 2012, 
              by = 10))             # Specify tick label sequence

axis(side = 4,                      # Add y-axis
     lwd = 0,                       # Remove axis line
     las = 1,                       # Rotate labels
     col.axis = "#dddddd",           # Adjust label colors
     at = seq(from = 0,             # Specify axis values
              to = 9, 
              by = 1), 
     font.axis = 2)  # Set labels to bold


lines(league.year,league.ave, col = "#0f618a", pch = 20, cex = 1, type = "o", lwd = 2)
segments( x0=1898, y0=8.5, x1=1904, y1=8.5, col="#0f618a", lwd = 1.5 )
points( x=c(1898,1904), y=c(8.5,8.5), col="#0f618a", pch=20, cex=1.2 )
text ( x=1912, y=8.5, col="#0f618a", labels=substitute(bold("League average")), cex=0.8 )
abline(h=0:9, col="gray", lty=3)


text(x = 1912, y = 11, labels = "Strikeouts on the Rise", cex = 1.5, col = "#000000")
text(x = 1930, y = 10.3, labels = "There were more strikeouts in 2012 than at any other time in major league history.", cex = 1, col= "#333333")
text(x = 1906, y = 9.1, labels = substitute(paste(bold('Strikeouts per game per team'))), cex = .8)
text(x = 1919, y = 9.1, labels = '(by batters)', cex = .8, col = "#999999")

text(x=1968, y=8.5,labels = substitute(bold("Pitching had become so dominant\nin the 1960s that the mound\n was lowered in 1969")), col = "#999999", cex = 0.8)

segments(y0=6, y1 = 8, x0= 1968, col = "#999999", lty=1, lwd = 0.5)

text(x=2008, y=3.5,labels = substitute(bold("Mitchell report\nof steroids")), col = "#999999", cex = 0.8)

segments(y0=3.9, y1 = 6.8, x0= 2008, col = "#999999", lty=1, lwd = 0.5)


text(x=1974, y=1.5,labels = substitute(bold("Designated hitter\nrule took effect")), col = "#999999", cex = 0.8)

segments(y0=1.9, y1 = 5, x0= 1974, col = "#999999", lty=1, lwd = 0.5)


text(x=1963, y=2.5,labels = substitute(bold("Strike zone enlagred\nfrom 1963-68")), col = "#999999", cex = 0.8)
segments(y0=2.9, y1 = 5.1, x0= 1963, col = "#999999", lty=1, lwd = 0.5)

text(x=1946, y=1.5,labels = substitute(bold("Players return\nfrom World War ƖƖ.")), col = "#999999", cex = 0.8)
segments(y0=1.9, y1 = 3.9, x0= 1946, col = "#999999", lty=1, lwd = 0.5)


text(x=1916, y=1,labels = substitute(bold("U.S. enters\nWorld War Ɩ.")), col = "#999999", cex = 0.8)
segments(y0=1.2, y1 = 3.4, x0= 1916, col = "#999999", lty=1, lwd = 0.5)



points(x = 2012, y = max(league.ave),pch=1, cex=2)
text(x = 2012, y = 7.9, labels = substitute(paste(bold('7.5'))), cex = 1.5, col="#0f618a")
text(x = 2012, y = 8.3, labels = substitute(paste(bold('League average'))), cex = .8)
text(x = 2012, y = 8.6, labels = substitute(paste(bold('2012'))), cex = .8)

points(x = 1924, y = league.ave[25],pch=1, cex=2)
text(x = 1924, y = 2.2, labels = substitute(paste(bold('2.7'))), cex = 1.5, col="#0f618a")
text(x = 1924, y = 1.89, labels = substitute(paste(bold('League average'))), cex = .8)
text(x = 1924, y = 1.6, labels = substitute(paste(bold('1924'))), cex = .8)


## GENERALIZED TEAM NAME:


# adding season stats for the team:
dat.one.team <- filter( Teams, name == team.name )
lines(x=dat.one.team$yearID, y=dat.one.team$ave.so, col = "goldenrod1", pch = 20, cex = 1, type = "o", lwd = 2)


# adding the team name to the legend:
segments( x0=1898, y0=8, x1=1904, y1=8, col="goldenrod1", lwd = 1.5 )
points( x=c(1898,1904), y=c(8,8), col="goldenrod1", pch=20, cex=1.2 )
text ( x=1912, y=8, col="goldenrod1", labels=substitute(bold(team.name)), cex=0.8 )



  
})

```



